"""Generate Discord knowledge cards from documentation content."""

import json
import os
from pathlib import Path
from typing import Any

import anthropic

from .card_store import CardStore

BUILD_DIR = Path(__file__).resolve().parent.parent / "build"


class ContentGenerator:
    """Splits documentation into knowledge cards for Discord posting."""

    def __init__(self, store: CardStore | None = None):
        self.store = store or CardStore()
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise RuntimeError("ANTHROPIC_API_KEY required")
        self.client = anthropic.Anthropic(api_key=api_key)

    def load_content_index(self) -> list[dict[str, Any]]:
        """Load the content index generated by build_all.py."""
        index_path = BUILD_DIR / "content_index.json"
        if not index_path.exists():
            raise FileNotFoundError(
                f"Content index not found at {index_path}. Run 'python scripts/build_all.py' first."
            )
        return json.loads(index_path.read_text(encoding="utf-8"))

    def generate_cards_for_page(self, page: dict[str, Any]) -> list[dict[str, Any]]:
        """Generate 2-4 knowledge cards from a single docs page.

        Each card has: title, summary (2-3 sentences), insight, tags.
        """
        response = self.client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=2048,
            system=(
                "You generate concise knowledge cards from technical documentation. "
                "Each card should be a standalone insight that makes sense without the full article. "
                "Target audience: solution engineers with data science background."
            ),
            messages=[{
                "role": "user",
                "content": (
                    f"Generate 2-4 knowledge cards from this documentation page.\n\n"
                    f"Title: {page['title']}\n"
                    f"Project: {page['project']}\n\n"
                    f"Content:\n{page['content'][:6000]}\n\n"
                    f"Return a JSON array of objects with keys: "
                    f"title, summary (2-3 sentences), insight (one key takeaway), "
                    f"tags (array of 2-3 tech terms).\n"
                    f"Return ONLY the JSON array, no markdown fences."
                ),
            }],
        )

        try:
            cards = json.loads(response.content[0].text)
        except json.JSONDecodeError:
            return []

        return cards

    def generate_all_cards(self, project: str | None = None) -> int:
        """Generate cards for all pages (or a specific project) and store them.

        Returns number of cards generated.
        """
        index = self.load_content_index()
        if project:
            index = [p for p in index if p["project"] == project]

        total = 0
        for page in index:
            print(f"  Generating cards for: {page['title']}")
            cards = self.generate_cards_for_page(page)
            for card in cards:
                self.store.add_card(
                    project=page["project"],
                    title=card.get("title", page["title"]),
                    summary=card.get("summary", ""),
                    insight=card.get("insight", ""),
                    tags=card.get("tags", []),
                    source_path=page["path"],
                    source_url=page.get("url", ""),
                )
                total += 1

        print(f"  Generated {total} cards")
        return total
